### ISSUE TITLE
요구분석서작성

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/SmartPot#1]
@Deockyoung @pyj9293 요구분석서 작성 바랍니다
경로 : 드라이브/여름지기/1.요구분석/요구분석서

**Comment by pyj9293** [comment]
> @Deockyoung 요구분석서 작성 바랍니다
> 경로 : 드라이브/여름지기/1.요구분석/요구분석서

요구분석서 작성완료했습니다
내용 :

**Comment by Deockyoung** [comment]
@pyj9293 
> 요구분석서 작성 바랍니다

완료했습니다.

**Comment by pyj9293** [comment]
> 완료했습니다. 

@Deockyoung 검토했습니다.

**Comment by pyj9293** [comment]
@Deockyoung 요구분석명세서 작성 완료 했습니다

요구분석명세서 : 여름지기/1.요구분석/요구분석명세서

검토 바랍니다
