### ISSUE TITLE
요구사항 명세서 

### ISSUE THREAD

**Issue by Deockyoung** [pyj9293/SmartPot#2]
@Deockyoung @pyj9293 요구사항 명세서 작성 바랍니다
경로 : 드라이브/여름지기/1.요구분석/요구사항 명세서

**Comment by Deockyoung** [comment]
@pyj9293 

> 요구사항 명세서 작성 바랍니다

작성 완료했습니다 검토바랍니다.

**Comment by pyj9293** [comment]
@Deockyoung [요구분석명세서](https://docs.google.com/spreadsheets/d/1KYVaoI1IJ90ErpDRW1-ZYMgncUUQwemCJeRBGBNeWOc/edit#gid=0) 작성 완료 했습니다

검토 바랍니다

**Comment by Deockyoung** [comment]
@pyj9293

검토했습니다.
